import react from "@vitejs/plugin-react"
import "dotenv/config"
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs"
import { createHash } from "crypto"
import { dirname, join, resolve } from "path"
import { fileURLToPath } from "url"
import { build } from "vite"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")
const DIST = join(ROOT, "dist")
const WEBSITES_PRESENCES = join(ROOT, "..", "..", "packages", "websites", "dist", "presences")
const GENERATED_DIR = join(ROOT, "src", "generated")

const webBaseUrl = process.env.VITE_WEB_BASE_URL ?? "https://nowly.me"
const apiBaseUrl = process.env.VITE_API_BASE_URL ?? "https://api.nowly.me"
const cdnBaseUrl = process.env.VITE_CDN_BASE_URL ?? "https://cdn.nowly.me"

const define = {
  "import.meta.env.VITE_WEB_BASE_URL": JSON.stringify(webBaseUrl),
  "import.meta.env.VITE_API_BASE_URL": JSON.stringify(apiBaseUrl),
  "import.meta.env.VITE_CDN_BASE_URL": JSON.stringify(cdnBaseUrl),
}

const buildPage = async (name: string, source = name) => {
  await build({
    root: join(ROOT, "src", source),
    base: "./",
    plugins: [react()],
    define,
    resolve: {
      alias: {
        "@": resolve(ROOT, "src"),
        "@messages": resolve(ROOT, "messages"),
      },
    },
    build: {
      outDir: join(DIST, name),
      emptyOutDir: true,
      rollupOptions: { input: join(ROOT, "src", source, "index.html") },
    },
    configFile: false,
  })
}

const buildScript = async (name: string, entry: string) => {
  await build({
    root: ROOT,
    define,
    resolve: {
      alias: {
        "@": resolve(ROOT, "src"),
        "@messages": resolve(ROOT, "messages"),
      },
    },
    build: {
      outDir: DIST,
      emptyOutDir: false,
      lib: {
        entry,
        formats: ["iife"] as const,
        name: `__presences_${name}`,
        fileName: () => `${name}.js`,
      },
      rollupOptions: {
        external: [],
      },
    },
    configFile: false,
  })
}

const copyManifest = () => {
  const manifest = JSON.parse(readFileSync(join(ROOT, "manifest.json"), "utf-8"))
  manifest.background.service_worker = "background.js"
  delete manifest.background.type
  manifest.content_scripts[0].js = ["content.js"]
  delete manifest.action.default_popup
  manifest.side_panel.default_path = "sidepanel/index.html"
  manifest.icons = {
    16: "icons/icon16.png",
    48: "icons/icon48.png",
    128: "icons/icon128.png",
  }
  manifest.action.default_icon = { ...manifest.icons }
  writeFileSync(join(DIST, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`)
}

const copyStatic = () => {
  mkdirSync(join(DIST, "icons"), { recursive: true })
  for (const size of [16, 48, 128]) {
    copyFileSync(
      join(ROOT, "src", "icons", `icon${size}.png`),
      join(DIST, "icons", `icon${size}.png`),
    )
  }
  copyFileSync(join(ROOT, "..", "web", "public", "app_title_white.png"), join(DIST, "app_title_white.png"))
  cpSync(join(ROOT, "_locales"), join(DIST, "_locales"), { recursive: true })
}

const canonicalJson = (value: unknown): string => {
  if (value === null || typeof value !== "object") return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`
  const object = value as Record<string, unknown>
  return `{${Object.keys(object)
    .filter((key) => object[key] !== undefined)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalJson(object[key])}`)
    .join(",")}}`
}

const sha256Base64Url = (input: string): string => {
  const hash = createHash("sha256").update(input).digest()
  return hash.toString("base64url")
}

const generateBundledPresences = (): void => {
  if (!existsSync(WEBSITES_PRESENCES)) {
    console.error("Presences not built. Run `pnpm presence build` first.")
    process.exit(1)
  }

  const dirs = readdirSync(WEBSITES_PRESENCES, { withFileTypes: true })
    .filter((d) => d.isDirectory())

  const entries: { slug: string; release: any }[] = []

  for (const dir of dirs) {
    const slug = dir.name
    const bundlePath = join(WEBSITES_PRESENCES, slug, "bundle.js")
    const metadataPath = join(WEBSITES_PRESENCES, slug, "metadata.json")

    if (!existsSync(bundlePath) || !existsSync(metadataPath)) continue

    const bundle = readFileSync(bundlePath, "utf-8")
    const metadata = { ...JSON.parse(readFileSync(metadataPath, "utf-8")), slug }

    const sha256 = sha256Base64Url(bundle)
    const metadataHash = sha256Base64Url(canonicalJson(metadata))

    entries.push({
      slug,
      release: {
        slug,
        version: metadata.version,
        metadata,
        bundle,
        sha256,
        metadataHash,
        signature: "",
        signedAt: new Date().toISOString(),
      },
    })
  }

  mkdirSync(GENERATED_DIR, { recursive: true })
  writeFileSync(
    join(GENERATED_DIR, "bundled-presences.ts"),
    `// Auto-generated by build-dev.ts — do not edit manually
import type { PresenceRelease } from "@/shared/types"

export interface BundledPresence {
  slug: string
  release: PresenceRelease
}

export const BUNDLED_PRESENCES: BundledPresence[] = ${JSON.stringify(entries, null, 2)}
`,
  )

  console.log(`  ✔ Bundled ${entries.length} presences`)
}

await generateBundledPresences()
await buildPage("sidepanel", "app")
await buildScript("background", join(ROOT, "src", "background", "index.ts"))
await buildScript("content", join(ROOT, "src", "content", "index.ts"))
copyManifest()
copyStatic()
